name: Node CI

on: [push]

jobs:
  build:
    
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [v.x]

    steps:
    - uses: actions/checkout@v1
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build application
      run: |
        npm install -g electron-packager
        make

#    - name: npm install, build, and test
#      run: |
#        npm ci
#        npm run build --if-present
#        npm test
#      env:
#        CI: true
